[[redirects]]
  from = "https://seoulair.netlify.app/*"
  to = "http:///seoulair.netlify.app/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://seoulair.netlify.app//*"
  to = "http:///seoulair.netlify.app/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http:///seoulair.netlify.app/*"
  to = "https:///seoulair.netlify.app/:splat"
  status = 301
  force = true